### ISSUE TITLE
Quotation - Undefined property: stdClass::$item

### ISSUE THREAD

**Issue by prhost** [foodkit/lalamove-php-api#12]
Hello,

I'm getting this error when returning the quote, it seems that the item is not returned within the response object.

```
ErrorException: Undefined property: stdClass::$item in /app/vendor/foodkit/lalamove-php-api/src/Responses/V3/QuotationResponse.php:77
Stack trace:
#0 /app/vendor/foodkit/lalamove-php-api/src/Responses/V3/QuotationResponse.php(77): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Undefined prope...', '/app/vendor/foo...', 77)
#1 /app/vendor/foodkit/lalamove-php-api/src/Resources/V3/QuotationsResource.php(17): Lalamove\Responses\V3\QuotationResponse->__construct(Object(stdClass))
```

<img width="867" alt="Screenshot 2022-08-04 at 23 20 09" src="https://user-images.githubusercontent.com/3984760/182987999-147e516e-f281-4e0d-9612-6fd6dc6738aa.png">

**Comment by prhost** [comment]
I tried to solve the problem by checking if the item property exists, but it caused another error because when you set $this->item null, the item property of the class is of type Item, causing the error below:

<img width="800" alt="Screenshot 2022-08-04 at 23 43 20" src="https://user-images.githubusercontent.com/3984760/182990533-89af7e51-15a0-4d96-9d85-a865900bed3d.png">

<img width="468" alt="Screenshot 2022-08-04 at 23 43 15" src="https://user-images.githubusercontent.com/3984760/182990540-f748c7d7-23bf-42d4-a3c5-66aef83f3dc3.png">


This problem will probably happen with priceBreakdown because its type is also defined.

<img width="394" alt="Screenshot 2022-08-04 at 23 45 31" src="https://user-images.githubusercontent.com/3984760/182990676-c5c76710-0877-4bdc-9ffb-540ce64e5539.png">
